name: Continous delivery

on:
  push:
    branches: [ docker-image ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myapp:$(git rev-parse --short HEAD)
