name: Continous delivery

on: [ push ]
#  workflow_run:
#    workflows: [ "Continous Integration" ]
#    types: [ completed ]
#    branches: [ master ]

jobs:
  on-success:
    runs-on: ubuntu-latest
  #  if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 1
        labels: 1

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag myapp:$(git rev-parse --short HEAD)
