name: Pylint 

on: [push]

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Static code analysis with pylint
      run: |
        pylint $(git ls-files '*.py')
